sys/dev/hptmv/ioctl.c:240:4: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]                         _vbus_p=pArray->pVBus;                         ^ sys/dev/hptmv/ioctl.c:237:10: note: previous statement is here                 if(!mIsArray(pArray))                 ^
This is because the return statement after the if statement was not
indented.  (Note that this file has been idented assuming 4-space tabs.)